FROM adoptopenjdk/openjdk11:alpine

ARG JAR_FILE=balanceservice/target/*.jar
COPY ${JAR_FILE} app.jar

WORKDIR /home/balance-service

RUN apk update && apk add bash

ENTRYPOINT ["java","-jar","/app.jar"]